fixtures:
  repositories:
    stdlib: 
      repo: 'git://github.com/puppetlabs/puppetlabs-stdlib.git'
    concat:
      repo: 'https://github.com/puppetlabs/puppetlabs-concat.git'
#  symlinks:
#    "syslog_ng": "#{source_dir}"
