fixtures:
  repositories:
     stdlib:
       repo: "https://github.com/puppetlabs/puppetlabs-stdlib.git"
       ref: 4.5.0
     concat:
       repo: "https://github.com/puppetlabs/puppetlabs-concat.git"
       ref: 2.0.0
#  symlinks:
#    patterndb: "#{source_dir}"
