language: ruby
rvm:
  - 2.1.9
  - 2.3.4
  - 2.4.1
before_script:
  - bundle install
  - bundle exec puppet --version
script:
  - bundle exec puppet module build
  - bundle exec puppet module install pkg/*.tar.gz
  - bundle exec rake spec
env:
  matrix:
    - PUPPET_GEM_VERSION="~> 4.9.1"   FIXTURES_YML=.fixtures-old.yml
    - PUPPET_GEM_VERSION="~> 4" FIXTURES_YML=.fixtures-old.yml
    - PUPPET_GEM_VERSION="~> 5.4.0"   FIXTURES_YML=.fixtures-old.yml
    - PUPPET_GEM_VERSION="~> 5"   FIXTURES_YML=.fixtures-old.yml
    - PUPPET_GEM_VERSION="~> 4.9.1"   FIXTURES_YML=.fixtures.yml
    - PUPPET_GEM_VERSION="~> 4" FIXTURES_YML=.fixtures.yml
    - PUPPET_GEM_VERSION="~> 5.4.0"   FIXTURES_YML=.fixtures.yml
    - PUPPET_GEM_VERSION="~> 5"   FIXTURES_YML=.fixtures.yml
gemfile: Gemfile
notifications:
  email: false
